### ISSUE TITLE
Value maps with "on" and "off" human-readable values are published to MQTT as "True" and "False"

### ISSUE THREAD

**Issue by tjhowse** [tjhowse/modbus4mqtt#7]
```yaml
  - pub_topic: "load_control/on_off"
    value_map:
      on: 170
      off: 85
    address: 13010
```

`modbus4mqtt/load_control/on_off False`
